<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @property integer $id
 * @property string $type
 * @property integer $identifier
 * @property string $name
 * @property string $logo
 * @property string $status
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property User[] $users
 * @property Message[] $messages
 *
 * @mixin Builder
 */
class Chat extends Model
{
    use HasFactory;

    const
        TYPE_MY_QUESTION = 'my_question',
        TYPE_TASK = 'task';

    const
        STATUS_CURRENT = 'current',
        STATUS_HISTORY = 'history',
        STATUS_SUPPORT = 'support';

    protected $fillable = [
        'type', 'identifier', 'name', 'logo', 'status', 'last_message_id'
    ];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function messages()
    {
        return $this->hasMany(Message::class);
    }

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
    }
}
